# Generated by Django 3.0.5 on 2020-06-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=250)),
                ('size', models.CharField(choices=[('X', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('I', 'Extra Large')], default='X', max_length=1)),
                ('quantity', models.IntegerField()),
                ('category', models.TextField(max_length=100)),
            ],
        ),
    ]
