# Generated by Django 3.0.5 on 2020-06-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='cart',
            name='ordered_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
